favicon: https://gcore.jsdelivr.net/gh/ccknbc-backup/cdn/logo/logo.png
banner: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/webstack_banner_cn.png

logo:
  expanded: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/logo@2x.png
  collapsed: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/logo-collapsed@2x.png
  dark: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: ç®€ä½“ä¸­æ–‡

search: true

githubCorner: false

menu:
  - name: ä¸æˆ‘ç›¸å…³
    icon: far fa-star
    submenu:
      # - name: å­¦ä¹ å‚è€ƒ
      #   icon: fas fa-tools
      #   config: å­¦ä¹ å‚è€ƒ
      # - name: èƒŒè¯µç›´è¾¾
      #   icon: fas fa-tools
      #   config: èƒŒè¯µç›´è¾¾
      - name: ä¸ªäººç«™ç‚¹
        icon: fas fa-star
        config: ä¸ªäººç«™ç‚¹
      - name: æœ‹å‹æ¨è
        icon: fas fa-tools
        config: æœ‹å‹æ¨è
  # - name: å¸¸ç”¨å·¥å…·
  #   icon: far fa-star
  #   submenu:
  #     - name: æ‰‹å†Œé€ŸæŸ¥
  #       icon: fas fa-book
  #       config: æ‰‹å†Œé€ŸæŸ¥
  #     - name: å‚è€ƒèµ„æ–™
  #       icon: fas fa-book
  #       config: å‚è€ƒèµ„æ–™
  #     - name: å›¾åºŠå·¥å…·
  #       icon: fas fa-file-image
  #       config: å›¾åºŠå·¥å…·
  #     - name: ç«™é•¿å·¥å…·
  #       icon: fas fa-tools
  #       config: ç«™é•¿å·¥å…·
  #     - name: ç½‘ç»œèµ„æº
  #       icon: fas fa-tools
  #       config: ç½‘ç»œèµ„æº
  #     - name: ä¸»æœºåŸŸå
  #       icon: fas fa-tools
  #       config: ä¸»æœºåŸŸå
  # - name: çº¿ä¸Šæ“ä½œ
  #   icon: far fa-star
  #   submenu:
  #     - name: é‚®ç®±ç›¸å…³
  #       icon: fas fa-envelope
  #       config: é‚®ç®±ç›¸å…³
  #     - name: åœ¨çº¿å†™ä½œ
  #       icon: fas fa-edit
  #       config: åœ¨çº¿å†™ä½œ
  #     - name: æ–‡ä»¶å¤„ç†
  #       icon: fas fa-file
  #       config: æ–‡ä»¶å¤„ç†
  #     - name: é˜…è¯»å¹³å°
  #       icon: fas fa-book-open
  #       config: é˜…è¯»å¹³å°
  # - name: ç¨‹åºå‘˜ğŸ‘¨â€ğŸ’»
  #   icon: far fa-star
  #   submenu:
  #     - name: APIæ¥å£
  #       icon: fas fa-tools
  #       config: APIæ¥å£
  #     - name: æœç´¢å¼•æ“
  #       icon: fas fa-search
  #       config: æœç´¢å¼•æ“
  #     - name: èµ„æºå­˜å‚¨
  #       icon: fas fa-cloud
  #       config: èµ„æºå­˜å‚¨
  #     - name: ç¨‹åºå‘˜
  #       icon: fas fa-code-branch
  #       config: ç¨‹åºå‘˜
  #     - name: å¼€æºé¡¹ç›®
  #       icon: fas fa-code
  #       config: å¼€æºé¡¹ç›®
  #     - name: æ·å¾„ç›´è¾¾
  #       icon: fas fa-space-shuttle
  #       config: æ·å¾„ç›´è¾¾
  # - name: ç´ æèµ„æº
  #   icon: far fa-star
  #   submenu:
  #     - name: å›¾ç‰‡ç´ æ
  #       icon: fas fa-tools
  #       config: å›¾ç‰‡ç´ æ
  #     - name: æ¸å˜é…è‰²
  #       icon: fas fa-tools
  #       config: æ¸å˜é…è‰²

testPage:
  - name: Child Page
    url: /child
    img: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/logos/myblog.png
    description: å­é¡µé¢æµ‹è¯•
devTools:
  - name: Github
    url: https://github.com/
    img: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/images/logos/github.png
    description: é¢å‘å¼€æºåŠç§æœ‰è½¯ä»¶é¡¹ç›®çš„æ‰˜ç®¡å¹³å°ã€‚

myBlog:
  - name: CCçš„éƒ¨è½æ ¼
    url: https://blog.ccknbc.cc/
    img: https://gcore.jsdelivr.net/gh/ccknbc-backup/cdn/logo/logo.png
    description: ä¸€ä¸ªæ‡’äººçš„åšå®¢ã€‚

about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

aboutPage:
  website:
    head: å…³äºæœ¬ç«™
    html: '<blockquote><p>æœ¬ç«™æ˜¯hexoä¸»é¢˜<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>çš„ç½‘å€æ”¶è—ç«™ã€‚</p></blockquote>'
  webmaster:
    head: å…³äºç«™é•¿
    name: CCåº·çº³ç™¾å·
    url: https://www.ccknbc.cc
    img: https://gcore.jsdelivr.net/gh/ccknbc-backup/cdn/logo/logo.png
    description: ä¸€ä¸ªæ— è¶£çš„äºº
    html: '<br /><blockquote><p>æœ¬ç«™æ˜¯<a href="https://github.com/HCLonely">HCLonely</a>åŸºäº<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>é¡¹ç›®åšçš„ä¸€æ¬¾<a href="https://hexo.io/">Hexo</a>ä¸»é¢˜ã€‚</p></blockquote>'

since: 2020
busuanzi:
  enable: false
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head:
  body:
    

js:
  header: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/header.min.js
  footer: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/footer.min.js
  jquery: https://gcore.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  bootstrap: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/bootstrap.min.js
  TweenMax: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/TweenMax.min.js
  resizeable: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/resizeable.min.js
  joinable: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/joinable.min.js
  xenonApi: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/xenon-api.min.js
  xenonToggles: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/xenon-toggles.min.js
  xenonCustom: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/xenon-custom.min.js
  lozad: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/lozad.min.js
  html5shiv: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/html5shiv.min.js
  respond: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # header: /js/header.js
  # footer: /js/footer.js
  # jquery: /js/jquery-1.11.1.min.js
  # bootstrap: /js/bootstrap.min.js
  # TweenMax: /js/TweenMax.min.js
  # resizeable: /js/resizeable.min.js
  # joinable: /js/joinable.js
  # xenonApi: /js/xenon-api.min.js
  # xenonToggles: /js/xenon-toggles.min.js
  # xenonCustom: /js/xenon-custom.min.js
  # lozad: /js/lozad.min.js
  # html5shiv: /js/html5shiv.min.js
  # respond: /js/respond.min.js
  # busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/hclonely.min.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/fonts/linecons/css/linecons.min.css
  fontawesome: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/fonts/fontawesome/css/all.min.css
  bootstrap: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/bootstrap.min.css
  xenonCore: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/xenon-core.min.css
  xenonComponents: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/xenon-components.min.css
  xenonSkins: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/xenon-skins.min.css
  nav: https://gcore.jsdelivr.net/gh/ccknbc-actions/blog-daohang@master/themes/webstack/source/css/nav.min.css
