favicon: https://cdn.jsdelivr.net/gh/sviptzk/StaticFile_HEXO@master/butterfly/img/favicon.ico
banner: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/images/webstack_banner_cn.png

logo:
  expanded: https://ae01.alicdn.com/kf/H1af96f32cca14859bb82b694059fbc2d3.png
  collapsed: https://ae01.alicdn.com/kf/H1af96f32cca14859bb82b694059fbc2d3.png
  dark: https://ae01.alicdn.com/kf/H1af96f32cca14859bb82b694059fbc2d3.png

flag:
  icon: flag-cn
  name: Chinese

githubCorner: '<a href="https://github.com/sviptzk/dh.xiaokang.me" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: å¸¸ç”¨å·¥å…·
    icon: far fa-star
    submenu:
      - name: æ‰‹å†Œé€ŸæŸ¥
        icon: fas fa-book
        config: æ‰‹å†Œé€ŸæŸ¥
      - name: å‚è€ƒèµ„æ–™
        icon: fas fa-book
        config: å‚è€ƒèµ„æ–™
      - name: å›¾åºŠå·¥å…·
        icon: fas fa-file-image
        config: å›¾åºŠå·¥å…·
      - name: ç«™é•¿å·¥å…·
        icon: fas fa-tools
        config: ç«™é•¿å·¥å…·
      - name: ç½‘ç»œèµ„æº
        icon: fas fa-tools
        config: ç½‘ç»œèµ„æº
      - name: ä¸»æœºåŸŸå
        icon: fas fa-tools
        config: ä¸»æœºåŸŸå
  - name: çº¿ä¸Šæ“ä½œ
    icon: far fa-star
    submenu:
      - name: é‚®ç®±ç›¸å…³
        icon: fas fa-envelope
        config: é‚®ç®±ç›¸å…³
      - name: åœ¨çº¿å†™ä½œ
        icon: fas fa-edit
        config: åœ¨çº¿å†™ä½œ
      - name: æ–‡ä»¶å¤„ç†
        icon: fas fa-file
        config: æ–‡ä»¶å¤„ç†
      - name: é˜…è¯»å¹³å°
        icon: fas fa-book-open
        config: é˜…è¯»å¹³å°
  - name: ç¨‹åºå‘˜ğŸ‘¨â€ğŸ’»
    icon: far fa-star
    submenu:
      - name: APIæ¥å£
        icon: fas fa-tools
        config: APIæ¥å£
      - name: æœç´¢å¼•æ“
        icon: fas fa-search
        config: æœç´¢å¼•æ“
      - name: èµ„æºå­˜å‚¨
        icon: fas fa-cloud
        config: èµ„æºå­˜å‚¨
      - name: ç¨‹åºå‘˜
        icon: fas fa-code-branch
        config: ç¨‹åºå‘˜
      - name: å¼€æºé¡¹ç›®
        icon: fas fa-code
        config: å¼€æºé¡¹ç›®
      - name: æ·å¾„ç›´è¾¾
        icon: fas fa-space-shuttle
        config: æ·å¾„ç›´è¾¾
  - name: ç´ æèµ„æº
    icon: far fa-star
    submenu:
      - name: å›¾ç‰‡ç´ æ
        icon: fas fa-tools
        config: å›¾ç‰‡ç´ æ
      - name: æ¸å˜é…è‰²
        icon: fas fa-tools
        config: æ¸å˜é…è‰²
  - name: ä¸æˆ‘ç›¸å…³
    icon: far fa-star
    submenu:
      - name: å­¦ä¹ å‚è€ƒ
        icon: fas fa-tools
        config: å­¦ä¹ å‚è€ƒ
      - name: èƒŒè¯µç›´è¾¾
        icon: fas fa-tools
        config: èƒŒè¯µç›´è¾¾
      - name: ä¸ªäººç«™ç‚¹
        icon: fas fa-star
        config: ä¸ªäººç«™ç‚¹
      - name: æœ‹å‹æ¨è
        icon: fas fa-tools
        config: æœ‹å‹æ¨è

about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

aboutPage:
  website:
    head: å…³äºæœ¬ç«™
    html: '<blockquote><p>æœ¬ç«™æ˜¯hexoä¸»é¢˜<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>çš„ç½‘å€æ”¶è—ç«™ã€‚</p></blockquote>'
  webmaster:
    head: å…³äºç«™é•¿
    name: å°åº·åšå®¢
    url: https://www.antmoe.com/
    img: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@latest/avatar.jpg
    description: ä¸€ä¸ªæ”¶è—å›å¿†ä¸åˆ†äº«æŠ€æœ¯çš„åœ°æ–¹ï¼
    html: '<br /><blockquote><p>æœ¬ç«™æ˜¯<a href="https://github.com/HCLonely">HCLonely</a>åŸºäº<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>é¡¹ç›®åšçš„ä¸€æ¬¾<a href="https://hexo.io/">Hexo</a>ä¸»é¢˜ã€‚</p></blockquote>'

since: 2020
busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head:
    - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/custom.css">
    - <script>var _hmt=_hmt||[];(function(){var hm=document.createElement("script");hm.src="https://hm.baidu.com/hm.js?b654aabd86db1f625ec9ecc4afad16e1";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm,s)})();</script>
  body:
    - <script src="https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/custom.min.js"></script>
js:
  header: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/header.js
  footer: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/footer.js
  jquery: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/jquery-1.11.1.min.js
  bootstrap: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/bootstrap.min.js
  TweenMax: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/TweenMax.min.js
  resizeable: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/resizeable.min.js
  joinable: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/joinable.js
  xenonApi: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/xenon-api.min.js
  xenonToggles: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/xenon-toggles.min.js
  xenonCustom: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/xenon-custom.min.js
  lozad: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/lozad.min.js
  html5shiv: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/html5shiv.min.js
  respond: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # header: /js/header.js
  # footer: /js/footer.js
  # jquery: /js/jquery-1.11.1.min.js
  # bootstrap: /js/bootstrap.min.js
  # TweenMax: /js/TweenMax.min.js
  # resizeable: /js/resizeable.min.js
  # joinable: /js/joinable.js
  # xenonApi: /js/xenon-api.min.js
  # xenonToggles: /js/xenon-toggles.min.js
  # xenonCustom: /js/xenon-custom.min.js
  # lozad: /js/lozad.min.js
  # html5shiv: /js/html5shiv.min.js
  # respond: /js/respond.min.js
  # busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/fonts/linecons/css/linecons.min.css
  fontawesome: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/fonts/fontawesome/css/all.min.css
  bootstrap: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/bootstrap.min.css
  xenonCore: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/xenon-core.min.css
  xenonComponents: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/xenon-components.min.css
  xenonSkins: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/xenon-skins.min.css
  nav: https://cdn.jsdelivr.net/gh/sviptzk/HexoStaticFile@master/webstack/css/nav.min.css
